### ISSUE TITLE
Add pose standard deviation to Web UI

### ISSUE THREAD

**Issue by asid61** [PhotonVision/photonvision#1013]
**Is your feature request related to a problem? Please describe.**
When I'm testing different camera configurations like exposure, brightness, threads, and iterations, I don't have an easy way of comparing the accuracy of two configs. This means I need a full control system setup and various logging steps to get the pose standard deviation from a camera.

**Describe the solution you'd like**
It would be nice to show the standard deviation of the pose (or multitag pose) over the last 5-10 seconds under or next to where the poses are shown. Sigma X, Y, and Theta(s) would be handy.

**Describe alternatives you've considered**
Running a control system, getting pose over NT, logging the pose, exporting the log, clearing out bad data, and using Excel/Sheets to find the pose standard deviation.

**Comment by mcm001** [comment]
Our code doesn't account for angle wrapping when calculating standard devs. Also weird barf in the console per Nolan -- also the targets pane will go poof sometimes

![](https://media.discordapp.net/attachments/725846797339066379/1186958667971563610/image.png?ex=65952467&is=6582af67&hm=6af6eae3d82304c6bd146635f02de00ed8c00fb13a2772c7b09723fa9c217596&)

**Comment by srimanachanta** [comment]
> Our code doesn't account for angle wrapping when calculating standard devs. Also weird barf in the console per Nolan -- also the targets pane will go poof sometimes
> 
> ![](https://camo.githubusercontent.com/f4260858918913e79bd1896e25050bfe9388bc6b64bad5a6289ca58a201bc99b/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3732353834363739373333393036363337392f313138363935383636373937313536333631302f696d6167652e706e673f65783d36353935323436372669733d363538326166363726686d3d3661663665616533643832333034633662643134363633356630326465303065643863303066623133613237373263376230393732336661396332313735393626)

the barf is due to #1030 

Neel to add an AngleModulus method but I'm not sure why because Rotation3d should already handle that

**Comment by mcm001** [comment]
Fixed locally PR incoming
