### ISSUE TITLE
Reported field-relative rotation appears to be in units other than degrees

### ISSUE THREAD

**Issue by asid61** [PhotonVision/photonvision#1025]
When I rotate a multitag target, the fused heading does not seem to change at the same rate as the Z angle change. ![image](https://github.com/PhotonVision/photonvision/assets/5743433/066f0f63-4070-47dd-8dcd-848d321d311a)

A 90deg tilt makes the reported Z angle change by 1.34. This appears to correspond to radians.

**Comment by mcm001** [comment]
Line 105 is missing degrees to radians. Easy fix for someone to PR

https://github.com/PhotonVision/photonvision/blob/master/photon-client/src/components/dashboard/tabs/TargetsTab.vue
