### ISSUE TITLE
Deferred store accessors don't correctly update on settings changes

### ISSUE THREAD

**Issue by srimanachanta** [PhotonVision/photonvision#1030]
When using deferred store accessors, the values within the accessor arent correctly updating which settings are changed on another deferred store. This is best seen in the multitag + targets tab relationship where changes in one deferred store arent reflected in the other. The backend is correctly receiving the requested change so this is a UI issue.

**Comment by mcm001** [comment]
This is the same issues as https://github.com/PhotonVision/photonvision/issues/1071 right?

**Comment by srimanachanta** [comment]
> This is the same issues as https://github.com/PhotonVision/photonvision/issues/1071 right?

I don't believe so, deferred store access is a camera settings store issue. Might be cause the buffer isn't saved into local storage, maybe we wanna add that.
