### ISSUE TITLE
Change VisionSystemSim.addAprilTags to assume 36h11 tags

### ISSUE THREAD

**Issue by shueja** [PhotonVision/photonvision#1041]
https://github.com/PhotonVision/photonvision/blob/6db5bc5e0c439a2e794fb1b36e0840fc67642fc6/photon-lib/src/main/java/org/photonvision/simulation/VisionSystemSim.java#L259C52-L259C52

**Comment by amquake** [comment]
Camera frame visualization needs to be updated with wpilib beta-4 to use the AprilTag generation introduced by @r4stered in https://github.com/wpilibsuite/allwpilib/pull/5923 for 36h11 tags
