### ISSUE TITLE
Install Script can't install Java when using bookworm

### ISSUE THREAD

**Issue by Technologyman00** [PhotonVision/photonvision#1057]
**Describe the bug**
The install script can't install Java when using bookworm 

This package doesn't exist in apt for bookworm openjdk-11-jre-headless

**To Reproduce**
Use install scriptnon bookworm
Won't boot photonvision because no java

**Platform:**
 - Hardware Platform: Pi 5

**Additional context**
Can be overcome by installing default-jdk

**Comment by mcm001** [comment]
Swap this to 17 and report back? If so make a PR to change the install script over to 17?

**Comment by BytingBulldogs3539** [comment]
> Swap this to 17 and report back? If so make a PR to change the install script over to 17?

Swapping to 17 fixed this for me, guess I forgot to update that.

**Comment by srimanachanta** [comment]
@Technologyman00 Does the new install script work for you? Can this be closed?

**Comment by Technologyman00** [comment]
Yep I just tried it can confirm it works
