### ISSUE TITLE
Camera calibration does not take into account current rotation

### ISSUE THREAD

**Issue by mcm001** [PhotonVision/photonvision#1084]
IS: camera pinhole math is decoupled from current camera image rotation. This means using any non-zero rotation after calibration makes the calibration wrong.
S/B: camera calibration should be valid only for zero-degree rotated images, and coefficients should be "rotated" to match input image rotation.

**Comment by KangarooKoala** [comment]
Was this fixed by #1464?

**Comment by mcm001** [comment]
Da
