### ISSUE TITLE
Change PacketPublisher::accept to PacketPublisher::set

### ISSUE THREAD

**Issue by srimanachanta** [PhotonVision/photonvision#1087]
https://github.com/PhotonVision/photonvision/blob/ef039da728f101aae51ae476f1e37e512badba72/photon-targeting/src/main/java/org/photonvision/common/networktables/PacketPublisher.java#L33

This should be renamed to `set` to follow the rest of wpilib. Also, do we want to reimplement these changes in cpp as well?

**Comment by mcm001** [comment]
Since it's a NFC it's up to you :)
