### ISSUE TITLE
Raspberry CSI Camera Funky Exposure and Gain Problems

### ISSUE THREAD

**Issue by BytingBulldogs3539** [PhotonVision/photonvision#1091]
**Describe the bug**
  When using a Raspberry Pi camera v / CSI camera, setting exposure to 0 turns on auto exposure even through auto exposure is off. Exposure settings seem to almost "jump" between values when passing over .5. Seems like decimal values are not actually working seems like it is rounding to the closest whole number. Additionally, setting the camera gain to 0 will also enable a sort of auto gain control. 
OV9281 Specific
  Exposure on the innomaker ov9281 seems to do nothing below values of 6.0. Issues above still apply. 

**Platform:**
 - Hardware Platform (ex. Raspberry Pi 4, Windows x64): All RPI Versions
 - Network Configuration (Connection between the Radio and any devices in between, such as a Network Switch): Home networking
 - PhotonVision Version: dev-v2024.1.1-beta-3.2-31-gece521c9
 - Browser (with Version) (Chrome, Edge, Firefox, etc.): Chrome
 - Camera(s) Used: RPI Camera V3 and Innomaker OV9281

**Comment by mcm001** [comment]
Never change libcamera lmao
