### ISSUE TITLE
Driver Mode 180 Deg Not Working.

### ISSUE THREAD

**Issue by BytingBulldogs3539** [PhotonVision/photonvision#1096]
**Describe the bug**
While in driver mode rotation of 180 deg does not work.

**Platform:**
 - Hardware Platform (ex. Raspberry Pi 4, Windows x64): PI5
 - PhotonVision Version: dev-v2024.1.1-beta-3.2-31-gece521c9
 - Camera(s) Used: OV9281

**Comment by BytingBulldogs3539** [comment]
Setting rotation to 180 seems to happen on input frame once then the drivermodepipeline flips it right back.

**Comment by srimanachanta** [comment]
@BytingBulldogs3539 Can this be closed?
