### ISSUE TITLE
Camera View can be difficult to view during camera calibration

### ISSUE THREAD

**Issue by srimanachanta** [PhotonVision/photonvision#1113]
When calibrating a camera in PhotonClient, depending on screen size, it can be difficult to see the camera stream while also being able to click and manipulate the options for calibration. Here is an example:
<img width="1418" alt="image" src="https://github.com/PhotonVision/photonvision/assets/68172138/385fa815-e64a-49b7-a018-62619f7e0a3c">

**Comment by Juniormunk** [comment]
fixed by https://github.com/PhotonVision/photonvision/pull/1294
