### ISSUE TITLE
The raspberry pi image is asking for a password upon boot , which password do i use ?

### ISSUE THREAD

**Issue by pkonnoth** [PhotonVision/photonvision#1149]
**Describe the bug**
A clear and concise description of what the bug is and what the expected behavior should have been.

**To Reproduce**

**Screenshots / Videos**
If applicable, add screenshots to help explain your problem. Additionally, provide journalctl logs and settings zip export. If your issue is regarding the web dashboard, please provide screenshots and the output of the browser console.

**Platform:**
 - Hardware Platform (ex. Raspberry Pi 4, Windows x64):
 - Network Configuration (Connection between the Radio and any devices in between, such as a Network Switch):
 - PhotonVision Version:
 - Browser (with Version) (Chrome, Edge, Firefox, etc.):
 - Camera(s) Used:

**Additional context**

**Comment by BytingBulldogs3539** [comment]
It is the default raspberry pi login username "pi" password "raspberry"

**Comment by mcm001** [comment]
But why do you need to log in in the first place?
