### ISSUE TITLE
Total ram not reported correctly

### ISSUE THREAD

**Issue by rzblue** [PhotonVision/photonvision#1154]
Total ram is not reported correctly on Linux (in my case, Orange Pi, but raspi looks like it would be affected as well)

Looks like #1068 modified the ram commands and made both the CPU ram and used ram metrics use the same command

**Comment by rzblue** [comment]
<img width="202" alt="image" src="https://github.com/PhotonVision/photonvision/assets/13878527/f163b6f8-d4c8-45dd-b446-18e68a17296e">
screenshot for reference

**Comment by BytingBulldogs3539** [comment]
Can you post the output of "free -m"
