### ISSUE TITLE
PhotonPoseEstimator doesn't correctly load OpenCV libraries before using MULTI_TAG_PNP_ON_RIO strategy

### ISSUE THREAD

**Issue by oh-yes-0-fps** [PhotonVision/photonvision#1177]
When using the PhotonPoseEstimator to estimate the pose using a camera, if your primary strategy is multi-tag on RIO there will be a crash when seeing multiple tags.

This was discussed in Discord and was concluded that OpenCV was only being loaded in simulation and not on the real robot.

![image (1)](https://github.com/PhotonVision/photonvision/assets/55303619/0a631264-4418-4147-872e-dbc4b51ad26a)

**Comment by mcm001** [comment]
Take a look at how OpencvHelp loads it in sim. We should do this the first time the on coproc multi tag runs.

**Comment by mcm001** [comment]
Believe this should be fixed? Re-open if not.
