### ISSUE TITLE
Minor version release

### ISSUE THREAD

**Issue by theVerySharpFlat** [PhotonVision/photonvision#1191]
#1181 makes the library useable for C++ teams. Can we do a release to push these changes out to teams (or update the last release, if possible)?

**Comment by mcm001** [comment]
Shipped v2024.2.1, CI's running. Meant to get to this this weekend but went skiing instead :)))))))))

**Comment by theVerySharpFlat** [comment]
> Shipped v2024.2.1, CI's running. Meant to get to this this weekend but went skiing instead :)))))))))

No worries. Of all the weekends to go skiing, I must say it was the perfect one with the weather! Hope you had fun!
