### ISSUE TITLE
"Reset Samples" button for standard deviations freezes the page

### ISSUE THREAD

**Issue by Gold872** [PhotonVision/photonvision#1203]
**Describe the bug**
On the web interface, if multiple tags are in view, the standard deviation always stays at "NaN/100 Samples", and hitting the "Reset Samples" button freezes the page, I have to refresh it to be able to change any other settings or view camera streams.

**To Reproduce**
1. Set up an 3D April Tag pipeline with multi-tag estimation turned on
2. Have multiple tags in view
3. Click on "Reset Samples"

**Screenshots / Videos**
![image](https://github.com/PhotonVision/photonvision/assets/91761103/06579925-1de1-4827-97b4-6d86bd4375e5)

https://github.com/PhotonVision/photonvision/assets/91761103/2ba8252a-22d5-434c-9df3-d8955121b0fb

**Platform:**
 - Hardware Platform: Windows 10 Home 22H2
 - Network Configuration: Windows Localhost
 - PhotonVision Version: 2024.2.2
 - Browser: Chrome 121.0.6167.85
 - Camera Used: Microsoft Lifecam HD 3000

**Additional context**
This also seems to happen when running on a Raspberry Pi, but I couldn't get any footage of it.

**Comment by DevonRD** [comment]
This problem appears to happen regardless of whether there are targets in view, and seems to me like it is an infinite loop problem since both the backend and frontend throw no errors. Investigating further

**Comment by DevonRD** [comment]
Hunch was right, but that was a symptom of the real issue and not the cause. Fix incoming
