### ISSUE TITLE
Calibration is Batman

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision#1212]
**Describe the bug**
NaN NaN NaN NaN NaN NaN NaN Na

batman

**To Reproduce**
Do a calibration

**Screenshots / Videos**
![image](https://github.com/PhotonVision/photonvision/assets/4583662/221a9341-3b5c-40a2-8909-5ae7b6d00403)

**Platform:**
pi 3 

commit 5851509a9e53a5bae892bd76adedb0ad59999693

**Additional context**

**Comment by gerth2** [comment]
![image](https://github.com/PhotonVision/photonvision/assets/4583662/252664db-5d87-4f0c-b79a-b7f61cf6d3b1)
nan in details too

**Comment by mcm001** [comment]
Probably closed by 1214? can you test

**Comment by gerth2** [comment]
Yes, confirmed closed in v2024.2.4
