### ISSUE TITLE
Checkerboard Cal Broken for non-1"-boards

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision#1213]
**Describe the bug**
A clear and concise description of what the bug is and what the expected behavior should have been.

**To Reproduce**
Download a calibration board of any size other than 1"

![image](https://github.com/PhotonVision/photonvision/assets/4583662/ca788eda-97a2-4f5e-b9cc-09155ada66cc)

produces

![image](https://github.com/PhotonVision/photonvision/assets/4583662/d0708cca-fc76-491a-9a79-557dad8163cc)

**Platform:**
All

**Comment by srimanachanta** [comment]
Bruh, this code hasn't changed since old UI, what the heck

**Comment by gerth2** [comment]
Confirmed fixed in v2024.2.4
