### ISSUE TITLE
LED Dimming Doesn't Work on Gloworm

### ISSUE THREAD

**Issue by carlosgj** [PhotonVision/photonvision#124]
In the latest dev build (photonvision-dev-dev-13-g66a5fa8.jar), the Brightness slider in the Settings page doesn't dim a Gloworm's LEDs properly. If the slider is set to 100, the LEDs are fully on. If the slider is set to any other value, the LEDs are fully off.

**Comment by mcm001** [comment]
Thanks for noticing. This is to do with how we are (or aren't) handling PWM frequency ranges in the backend, I think. I'll look more into it.

**Comment by carlosgj** [comment]
FWIW, for "ledPWMFrequency", I've tried 30000 (per the Gloworm image) and 800 (per `photon-server/src/test/resources/hardware/HardwareConfig.json`) with no noticeable differences.

**Comment by mcm001** [comment]
This seems to be related to an integer division bug in PiGPIO.

**Comment by Bankst** [comment]
Fixed  in #127, awaiting further testing to confirm

**Comment by pietroglyph** [comment]
Confirmed working on my Gloworm too.
