### ISSUE TITLE
Camera Exposure Control Doesn't Work on Gloworm

### ISSUE THREAD

**Issue by carlosgj** [PhotonVision/photonvision#125]
The camera shutter speed seems to be 0 (or very small) when the exposure slider is set to 0, and some fixed value when the slider is greater than 1. 

The shutter should be able to be set from 1 to 6,000,000 microseconds (or some subset of that range).

**Comment by pietroglyph** [comment]
This is a known issue, and there are fixes in V4l2/CSCore to make this work correctly, but the camera backend on the Raspberry Pi 3 is going to be completely replaced with one that uses MMAL and does GPU acceleration (and incidentally does exposure control correctly) so we're going to wait to fix this until the GPU stuff gets merged.

**Comment by gerth2** [comment]
FYI: Confirmed something nearly identical with a Pi V2 camera and a Pi 4. 10-4 on waiting for new core to support it.

I do like the idea of setting/displaying it in terms of physical units - drives education at the UI level about what the underlying thing the user is actually tweaking.

**Comment by Bankst** [comment]
Fixed in #146
