### ISSUE TITLE
No library update for v2024.2.7

### ISSUE THREAD

**Issue by brhea** [PhotonVision/photonvision#1254]
Running v2024.2.6 on orange pi 5
Downloaded and updated to v2024.2.7 on orange pi
Rebooted robot and got the fatal error message that the library did not match the version of photonvision.
Tried to update the vscode library online and none was found. 
Reverted the software on the orange pi to v2024.2.6 and error went away.

library updates have previously worked with no issue.

**Comment by mcm001** [comment]
https://maven.photonvision.org/repository/internal/org/photonvision/photonlib-json/1.0/photonlib-json-1.0.json correctly shows 2024.2.7 for me....

**Comment by lorelaib182** [comment]
I tried the update again today and the update to the library worked properly. could have been a server problem yesterday?

**Comment by mcm001** [comment]
Oh nice! Maybe something weird and transient yeah. Feel free to reopen if necessary
