### ISSUE TITLE
Speed OrangePi boot time

### ISSUE THREAD

**Issue by fovea1959** [PhotonVision/photonvision#1259]
**Is your feature request related to a problem? Please describe.**
Trying to get vision booted as quickly as possible.

**Describe the solution you'd like**
Disable unneeded services that are shown by systemd-analyze to slow boot.
Disable network manager if static address set.

**Describe alternatives you've considered**
A short list:
* Disable the Bluetooth service. `systemctl disable ap6275p-bluetooth`
* Disable the cloud-init service. `touch /etc/cloud/cloud-init.disabled`
* Somehow get /etc/network/interfaces set correctly, and NetworkManager service disabled if a static address was requested.

...and changing the /etc/passwd entry for userid 'pi' to use bash instead of sh would be nice :)

**Comment by mcm001** [comment]
Big fan of stuff booting faster yeah. 

Wait, do we not kill Bluetooth and WiFi in our image yet? Yikes. We need to do that

**Comment by Juniormunk** [comment]
fixed in [#19](https://github.com/PhotonVision/photon-image-modifier/pull/19)
