### ISSUE TITLE
PhotonVision OjectDetection camera sometimes missing on boot

### ISSUE THREAD

**Issue by gartaud** [PhotonVision/photonvision#1273]
**Describe the bug**
This is a follow up from this tread on Chief Delphi: https://www.chiefdelphi.com/t/photonvision-ojectdetection-camera-sometimes-missing-on-boot/458083
(note: I am not the OP but we observe similar symptoms, so copied original text herehunder)

We have PhotonVision running on an Orange Pi 5 with one AprilTag and one ObjectDetection camera. We have an intermittent issue where the ObjectDetection pipeline doesn’t work on boot.

**To Reproduce**
The code reports the camera isn’t present and there is no data in the network table. When we check the web UI, it shows the yellow spinning image for that pipeline and the camera never comes up. The camera also does not appear on the Camera Settings page.

**Screenshots / Videos**
See CD thread

**Platform:**
 - Hardware Platform: Orange Pi 5
 - Network Configuration: D-link switch between Orange Pi 5 and Radio which is unlikely to play a role
 - PhotonVision Version: 2024.2.7 upgraded from 2024.2.6
 - Browser: both Chrome and Edge show symptoms
 - Camera(s) Used: Microsoft Lifecam 3000

**Additional context**
In our case we think that things were working fine for days before everything fell apart. We did not knowingly change anything that could explain the change.

**Comment by mcm001** [comment]
All the dmesg logs we've seen in Discord have shown the same symptoms at failure (something similar to this):
```
[ 2087.275215] Unable to handle kernel paging request at virtual address ffff000000000000
[ 2087.276237] Mem abort info:
[ 2087.276770]   ESR = 0x96000146
[ 2087.277365]   EC = 0x25: DABT (current EL), IL = 32 bits
[ 2087.278138]   SET = 0, FnV = 0
[ 2087.278718]   EA = 0, S1PTW = 0
[ 2087.279310] Data abort info:
[ 2087.279873]   ISV = 0, ISS = 0x00000146
[ 2087.280541]   CM = 1, WnR = 1
[ 2087.281128] swapper pgtable: 4k pages, 48-bit VAs, pgdp=0000000001d91000
[ 2087.282066] [ffff000000000000] pgd=00000000efff8003, p4d=00000000efff8003, pud=00000000efff7003, pmd=0000000000000000
[ 2087.283383] Internal error: Oops: 96000146 [#1] SMP
```

**Comment by gartaud** [comment]
Ok, thanks.

I'm not sure if you noticed the suggestion to run https://scan.coverity.com/ for free on your codebase in the linked CD thread. That should not take too long to put in place and might point out to things in your code that you oversaw.
