### ISSUE TITLE
Add unique result getter to PhotonCamera

### ISSUE THREAD

**Issue by TheTripleV** [PhotonVision/photonvision#1303]
getLatestResult() will return the same value again and again on repeated calls.

A getLatestUniqueResult -> Optional<...> could return the new result exactly once then return None and there's a new value available. This deduplication in the vendordep would make it easy to avoid overfeeding the pose estimator.

**Comment by mcm001** [comment]
Really we should figure out how to support providing a list of results (getatomic style?) I think
