### ISSUE TITLE
Yaw zero is way off in all modes when camera is rotated

### ISSUE THREAD

**Issue by asid61** [PhotonVision/photonvision#1414]
**Describe the bug**
When the selected camera is rotated, the yaw zero point for both 2D apriltag pipelines and object detection piplines are way off.
![image](https://github.com/user-attachments/assets/7be80232-0f49-4bf0-9acf-40261e574ff6)

**To Reproduce**
1. Create a new 2d apriltag pipeline
2. Set camera rotation to 90* CW
3. Hold up a tag the center of the screen. Yaw will not be zero. 
4. Moving the tag left or right somewhat will find the true zero.

**Screenshots / Videos**
I have attached an image showing where the yaw zero is on an OV9782 running note detection.

**Platform:**
 - Hardware Platform (ex. Raspberry Pi 4, Windows x64): Orange Pi 5
 - Network Configuration (Connection between the Radio and any devices in between, such as a Network Switch): VH-109 Radio
 - PhotonVision Version: dev-v2024.3.0-66-g06f0f7d6 (September 3rd)
 - Browser (with Version) (Chrome, Edge, Firefox, etc.): Chrome
 - Camera(s) Used: OV9782 and OV9281

**Additional context**

**Comment by Juniormunk** [comment]
fixed by #1464
