### ISSUE TITLE
Red balance does not show up on OV9782 camera

### ISSUE THREAD

**Issue by asid61** [PhotonVision/photonvision#1419]
**Describe the bug**
Arducam OV9782 has a random red balance every time I reboot the system. I cannot edit the red balance.

**To Reproduce**
1. Plug in an Arducam OV9782 into a Photonvision processor.

**Screenshots / Videos**
one on boot:
![image](https://github.com/user-attachments/assets/6f20685f-d853-441d-9a8b-287c1c34ad0f)
on another boot: 
![image](https://github.com/user-attachments/assets/beb90ed9-f9fa-4ffb-bb12-a1188c10da97)
and anotha
![image](https://github.com/user-attachments/assets/a8b6a807-db5e-42a2-aaf7-b4f6cda4c800)

**Platform:**
 - Hardware Platform (ex. Raspberry Pi 4, Windows x64): Orange Pi 5
 - Network Configuration (Connection between the Radio and any devices in between, such as a Network Switch): VH-109 Radio
 - PhotonVision Version: dev-v2024.3.0-66-g06f0f7d6
 - Browser (with Version) (Chrome, Edge, Firefox, etc.): Chrome
 - Camera(s) Used: OV9782

**Additional context**

**Comment by asid61** [comment]
Setting white balance via ssh + v4l2 CLI commands sory of works. The parameter is set, but the image does not change. Hue and Gain work normally. Below shows some of the v4l2 stuff.
![image](https://github.com/user-attachments/assets/6f1ea95c-8b95-485d-90be-cd7abb07e434)

Unplugging and replugging the camera did not fix this. The image became quite red. 
[photonvision-journalctl (7).txt](https://github.com/user-attachments/files/17004568/photonvision-journalctl.7.txt)

**Comment by asid61** [comment]
![image](https://github.com/user-attachments/assets/0a87a7b4-2b33-4e47-a05b-19df2825c190)
red image

**Comment by asid61** [comment]
v4l2-ctl commands for white balance work on the BREAD fork of PV here: https://github.com/BREAD5940/photon-image-modifier/releases/tag/Dev

**Comment by Juniormunk** [comment]
Fixed by #1477
