### ISSUE TITLE
Add Factory Reset Button

### ISSUE THREAD

**Issue by asid61** [PhotonVision/photonvision#1421]
**Is your feature request related to a problem? Please describe.**
Sometimes Photonvision fails in strange and unpredictable ways, especially when layering configs on an old install. 

**Describe the solution you'd like**
A way to completely restore PV to factory defaults would be great. A button on the Settings page would work fine for this. That would make it much easier to debug issues by asking people to save their settings, factory reset, and then just re-upload any camera calibrations.

**Describe alternatives you've considered**
In the past I have often just reflashed the SD card and spun everything up from scratch. Kind of a waste of time.

**Additional context**

**Comment by Juniormunk** [comment]
fixed by #1471
