### ISSUE TITLE
Changing to Aruco Pipeline crashes PV

### ISSUE THREAD

**Issue by asid61** [PhotonVision/photonvision#1422]
**Describe the bug**
Changing pipeline from Apriltag to Aruco on an OV9281 crashes PV until restarting it. After restart, the pipeline is restored to Apriltag.

**To Reproduce**
1. Make an Apriltag pipeline
2. Change it so an Aruco pipeline

**Screenshots / Videos**
I'll add these later

**Platform:**
 - Hardware Platform (ex. Raspberry Pi 4, Windows x64): Orange Pi 5
 - Network Configuration (Connection between the Radio and any devices in between, such as a Network Switch): VH-109
 - PhotonVision Version: photonvision-v2024.3.1
 - Browser (with Version) (Chrome, Edge, Firefox, etc.): Chrome
 - Camera(s) Used: OV9281, OV9782, Lifecam

**Additional context**

**Comment by mcm001** [comment]
When you get a chance, journalCTL logs would also be helpful. That's the export current run logs button.

**Comment by Juniormunk** [comment]
[photonvision-journalctl (1).txt](https://github.com/user-attachments/files/17004765/photonvision-journalctl.1.txt)

**Comment by cb144p** [comment]
Might be linked to issue #1338

**Comment by Juniormunk** [comment]
[hs_err_pid2383.log](https://github.com/user-attachments/files/17271125/hs_err_pid2383.log)
More info

**Comment by mcm001** [comment]
Good find! A kaboom inside the wpilib apriltag detector is kinda terrifying.
