### ISSUE TITLE
Add gain and white balance sliders

### ISSUE THREAD

**Issue by asid61** [PhotonVision/photonvision#1425]
**Is your feature request related to a problem? Please describe.**
Gain and white balance are often set badly on cameras, adding noise and color inaccuracy

**Describe the solution you'd like**
Add sliders for gain and white balance under the other sliders. It can be an an "advanced features" tab or dropdown to make it harder to change my accident for new users.

**Describe alternatives you've considered**
Setting it over V4l2 works but sucks

**Additional context**

**Comment by mcm001** [comment]
Should be covered by https://github.com/PhotonVision/photonvision/pull/1477 ? If any new cams need a gain slider, cut a new issue to add a Quirk.
