### ISSUE TITLE
5 digit team numbers

### ISSUE THREAD

**Issue by Juniormunk** [PhotonVision/photonvision#1474]
Allow 5 digit team numbers.

**Comment by mcm001** [comment]
Is this limitation in the UI or somewhere in backend code?

**Comment by crschardt** [comment]
I'm looking through the backend and it assumes that the team number is an integer and passes it to NetworkTablesJNI.setServerTeam(). Is it possible that we need to update ntcore to 2025 and 5-digit teams will work?

**Comment by Juniormunk** [comment]
Then my guess is just a UI limitation

**Comment by crschardt** [comment]
Why don't you think it's an ntcore 2024.3.2 limitation? Did WPILib support 5 digit team numbers in 2024?

**Comment by Juniormunk** [comment]
I'm not sure if they supported 5-digit teams but it doesn't matter. At some point we will have to update to 2025 and we will get those changes. But the main thing it looks like is a UI limitation checking for team numbers up to 9999

**Comment by Juniormunk** [comment]
ill put this in with the 2025 stuff tonight
