### ISSUE TITLE
AScope's struct decoding breaks in sim with error "Fixed length arrays are unimplemented"

### ISSUE THREAD

**Issue by TheComputer314** [PhotonVision/photonvision#1576]
See https://github.com/Mechanical-Advantage/AdvantageScope/issues/273
Unsure if this is Photon's fault or AScope's fault so putting this in both repos.

**Platform:**
 - WPILib 2025.1.1-beta-1
 - PhotonLib v2025.0.0-beta-1
 - AdvantageScope 4.0.0-beta-3
 - win32-x64

Tested on https://github.com/icrobotics-team167/2024_Off_Season/tree/WPILib2025

**Comment by mcm001** [comment]
Thanks This issue should be moved to ascope
