### ISSUE TITLE
UnsupportedClassVersionError when installing latest beta on Windows

### ISSUE THREAD

**Issue by jletroui** [PhotonVision/photonvision#1609]
**Describe the bug**
Trying to run on Windows, with the JDK version described in the documentation leads to:

``` 
~\Downloads> java -version
openjdk version "11.0.25" 2024-10-15
OpenJDK Runtime Environment Temurin-11.0.25+9 (build 11.0.25+9)
OpenJDK 64-Bit Server VM Temurin-11.0.25+9 (build 11.0.25+9, mixed mode)
~\Downloads> java -jar photonvision-v2025.0.0-beta-5-winx64.jar
Error: LinkageError occurred while loading main class org.photonvision.Main
        java.lang.UnsupportedClassVersionError: org/photonvision/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**To Reproduce**
1. Installed the requirements with `choco install -y vcredist-all Temurin11`
2. Download `photonvision-v2025.0.0-beta-5-winx64.jar` from the release page
3. Change directory to the download directory
4. Run the command `java -jar photonvision-v2025.0.0-beta-5-winx64.jar`

**Platform:**
 - Hardware Platform: Windows x64)
 - PhotonVision Version: v2025.0.0-beta-5
 - Browser: irrelevant
 - Camera(s) Used: irrelevant

**Workaround**

Installing Temurin17 is solving the issue.

**Comment by mcm001** [comment]
Related to https://github.com/PhotonVision/photonvision/issues/1604 - our docs need to require the wpilib jdk due to windows std mutex Abi break too
