### ISSUE TITLE
Limelight 2+ not booting with version 2025.0.0-beta-5

### ISSUE THREAD

**Issue by Astatin3** [PhotonVision/photonvision#1628]
**Describe the bug**
Using a limelight 2+, and 2025.0.0-beta-5 the device does not appear to boot.

**To Reproduce**
Flash the image with the recommended version of Balena Etcher

**Platform:**
 - Hardware Platform (ex. Raspberry Pi 4, Windows x64): Limelight 2+
 - Network Configuration: Laptop and limelight connected via router over ethernet.
 - PhotonVision Version: 2025.0.0-beta-5
 - Browser (with Version) (Chrome, Edge, Firefox, etc.): 2025.0.0-beta-5
 - Camera(s) Used: Whatever the Limelight 2+ has.

**Additional context**
- I was not at all using the most ideal setup, with a linux laptop writing data, and an undervolted limelight.
- I redownloaded and reflashed the image in case it was download error
- Limelight version 2024.10.2 flashed and worked fine
- Photonvision version 2024.3.1 flashed and worked fine

**Comment by Juniormunk** [comment]
Oh boy so much fun. Can you hook up a screen to it and send the console outputs?

**Comment by Astatin3** [comment]
With a working photon release, I can't get an HDMI output working over the USB-A port on the device, Is there a way I could view the logs outputted to the local storage?

**Comment by Astatin3** [comment]
After a fresh flash of 2024.3.1, I attempted to install beta-5 using the jar upload feature, the jar ran and the UI came up, but it didn't seem to detect any hardware. (Look at image below)
![15:40:33](https://github.com/user-attachments/assets/28141831-9e8f-4cfe-bb53-aff10c86067a)

I can try some more monitors in a couple days when I have access to them.

**Comment by Juniormunk** [comment]
Ahhh right I keep forgetting that limelight doesn't have a video output. Does it show up on the network? Can you ssh into it?

**Comment by Astatin3** [comment]
I don't believe so, but give me a minute to reflash the image and see if I can just in case.

**Comment by Astatin3** [comment]
Okay, for some reason it's working now. This is my first time working with PhotonVision, and I saw the green status LED that turns on with power inside the case of the limelight was blinking, which made me think it was some kind of bootloop. Thank you so much for your help! This was really just stupid on my end.
