### ISSUE TITLE
OpenCV loaded failed with WPILib 2025.1.1-beta-3 when simulating

### ISSUE THREAD

**Issue by RockyXRQ** [PhotonVision/photonvision#1635]
**Describe the bug**
OpenCV loaded failed with WPILib 2025.1.1-beta-3 when simulating

**To Reproduce**
1. just write `var sim = new PhotonCameraSim(camera, simCameraProperties)` in code
2. run `Simulate Robot Code`

**Screenshots / Videos**
![image](https://github.com/user-attachments/assets/bb63b778-9330-43d9-a268-bb16e82c166a)

**Platform:**
 - Hardware Platform: Windows x64
 - Network Configuration: LocalHost
 - PhotonVision Version: v2025.0.0-beta-6
 - Browser: None
 - Camera(s) Used: None

**Comment by mcm001** [comment]
Is opencv_java480d in the jar at the path it tried to extract from? Are you positive that you're using the jdk shipped with wpilib 2025 beta 2?

**Comment by mcm001** [comment]
Is opencv_java480d in the jar at the path it tried to extract from? Are you positive that you're using the jdk shipped with wpilib 2025 beta 2?

**Comment by RockyXRQ** [comment]
Seems I don't have that jar at the path, only bunch of .dll and .pdb file. I can run the simulator in 2025 beta 2 but not after updated to 2025 beta 3

**Comment by RockyXRQ** [comment]
I'm using a totally freshly installed wpilib 2025 vscode, so I guess I'm using the the jdk shipped with wpilib 2025 beta 2? Is there anyway to confrim that?

**Comment by RockyXRQ** [comment]
I have these in build/jni/release
![image](https://github.com/user-attachments/assets/74f58806-ba54-4cc7-bb22-3f519df4d8c6)

**Comment by mcm001** [comment]
Huh. So we're trying to load 4.8, but we only ship 4.10?

**Comment by spacey-sooty** [comment]
WPILib recently updated

**Comment by RockyXRQ** [comment]
Seems they did update it to 4.10 https://github.com/wpilibsuite/allwpilib/commit/c3fc7c829d2251bb65f29cbed452df1e8883c07d

**Comment by mcm001** [comment]
Wait hold on. Wat. You're using Beta 3? we only currently support beta 2. https://github.com/PhotonVision/photonvision/blob/master/build.gradle#L33

Try again using beta 2, or wait till we put out a release.

**Comment by mcm001** [comment]
I can run the sim fine using 2025 wpilib beta 2 vscode still. Reopen if you have issues using beta 2 still!
