### ISSUE TITLE
Allow JAR update from UI when run from service

### ISSUE THREAD

**Issue by Bankst** [PhotonVision/photonvision#249]

**Comment by gerth2** [comment]
Per Nov23 meeting - higher priority for kickoff

**Comment by gerth2** [comment]
Also per meeting - https://github.com/Chameleon-Vision/chameleon-vision/blob/master/chameleon-server/src/main/java/com/chameleonvision/web/RequestHandler.java#L226 has the basic functionality we're looking for.
