### ISSUE TITLE
PhotonLib: Add static/constants for each annual vision targets

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision#269]
Add easy-to-use `Pose` and `SimVisionTarget` C++/Java definitions for the 2020 game. Intent would be to keep updating these for each year of game that comes out.

This shouldn't prevent users from defining their own, but should help take out some of the tedium of sim setup.

**Comment by amquake** [comment]
With the move to AprilTags and WPILib-provided AprilTag field layouts, this is less relevant now.

There are still lots of other "poses of interest" in each year's field, but I'm not sure photonvision can supply those in a concise and useful manner for all teams.
