### ISSUE TITLE
The problem of Installing PhotonVision on Windows 10

### ISSUE THREAD

**Issue by mendax1234** [PhotonVision/photonvision#273]
l try to install the PhotonVision on my ThinkPadX390 but l meet some errors 

<img width="946" alt="error1" src="https://user-images.githubusercontent.com/62934294/118789839-c2bb7580-b8c7-11eb-9f81-88fccbdcf6d5.PNG">
<img width="960" alt="error2" src="https://user-images.githubusercontent.com/62934294/118789847-c5b66600-b8c7-11eb-8c63-f13b8d17cf40.PNG">

so how to solve it ?

**Comment by Bankst** [comment]
The only error in those logs is that it failed to connect to a NetworkTables server, which is expected when you are on a PC not connected to a robot network.

Have you opened the web interface? (http://localhost:5800)

**Comment by mendax1234** [comment]
No , l haven't . If I want to use it on my Limelight , so l just need to install the firmware on it and follow the steps on the official Limelight website?

**Comment by mcm001** [comment]
Gunna close this as it's been a hot sec. If you still need help please take a look at our discord, which you can join here:
discord.gg/wYxTwym
