### ISSUE TITLE
Update Checkerboard Along With Calibration Defaults

### ISSUE THREAD

**Issue by mdurrani808** [PhotonVision/photonvision#293]
The calibration tab defaults/autofills the fields to a 7x7 checkerboard with a 1in pattern. The downloadable checkerboard is 8x8, the default should be changed accordingly.

https://github.com/PhotonVision/photonvision-docs/pull/113
This PR contains a PDF of the checkerboard, we should link this instead of the PNG.

**Comment by gerth2** [comment]
https://github.com/PhotonVision/photonvision/pull/307 should also take care of this

**Comment by gerth2** [comment]
Also, if #307 is merged, the PDF in PhotonVision/photonvision-docs#113 could be tweaked to have the branding/ruler of the latest UI?
