### ISSUE TITLE
CI will push dev JSONs to Artifactory

### ISSUE THREAD

**Issue by mcm001** [PhotonVision/photonvision#299]
At https://maven.photonvision.org/repository/internal/org/photonvision/PhotonLib-json/1.0/PhotonLib-json-1.0.json , the version is currently `v2021.1.6-3-gf922466d`. This task should be skipped if it isn't a release.

**Comment by mcm001** [comment]
This appears to have been fixed? Should monitor

**Comment by Bankst** [comment]
Any update on this?

**Comment by mcm001** [comment]
No longer occurs at the URL linked above
