### ISSUE TITLE
Failure to install photonlib with WPILIB 2021.2.2

### ISSUE THREAD

**Issue by mendax1234** [PhotonVision/photonvision#305]
l use WPILIB 2021.2.2 , however , when l use the online installation command. And press enter after copy the url in it. Nothing seems to happen and l can't install it.

**Comment by mcm001** [comment]
Hey! Have you posted on Discord? That may be the best way to get support

**Comment by mendax1234** [comment]
NO, not yet. How to do it?

**Comment by mcm001** [comment]
https://discord.gg/n8Kfc3ED

**Comment by mendax1234** [comment]
Thanks！
