### ISSUE TITLE
Higher Stream Resolution

### ISSUE THREAD

**Issue by TateStaples** [PhotonVision/photonvision#310]
In driver mode, there is no way to get above a 320x240 stream resolution.

**Comment by Bankst** [comment]
Clarification: per Discord, OP is running PhotonVisionan on an LL2.

**Comment by mcm001** [comment]
https://github.com/PhotonVision/photonvision/blob/a2af7d9273e29d3115a0d9098c0c300a314b32e4/photon-client/src/views/PipelineViews/InputTab.vue#L173 is the issue. We limit it for latency reasons.

**Comment by mcm001** [comment]
We can remove this check in driver mode?
