### ISSUE TITLE
Photon Version Mismatch

### ISSUE THREAD

**Issue by MrRSquared** [PhotonVision/photonvision#320]
Hello,
I am struggling to get the new version of Photon running right now on new projects. The issue is that I have an older version of Photon on the device (Romi), but when I attempt to connect to it, I get a version of the following error.

`Photon version v2021.1.8 does not match coprocessor version dev!`

I can use the old version on the Romi and modify the vendor lib .Json in my robot program (to v2021.1.7), but the new version is registering as Dev so the current .Json it will not connect to the library. Is this expected behavior?

**Comment by mcm001** [comment]
Identified as a CI issue. Again.

**Comment by mcm001** [comment]
Hopefully addressed in #328

**Comment by MrRSquared** [comment]
Thank you. I am sorry if this was posted elsewhere and I did not see it.

**Comment by icemannie** [comment]
Getting the same issue on Gloworm v2021.1.3 running on a Limelight 2. Had another issue in that after flashing the Limelight the hardware on fig.json wouldn’t load.

**Comment by mdurrani808** [comment]
Pending further updates, going to close this. Haven't gotten any more reports.
