### ISSUE TITLE
Add C++ example code for simposeest

### ISSUE THREAD

**Issue by mdurrani808** [PhotonVision/photonvision#333]

**Comment by gaborszita** [comment]
Will this be implemented in the 2023 photonvision release?

**Comment by mdurrani808** [comment]
Hi, we don't currently have C++ code for the simulation pose estimation and don't currently have the bandwidth to write it at the moment. I'll see if anyone has the time. Otherwise, the Java code has all the logic down and should be easy to port to C++.

**Comment by amquake** [comment]
> Will this be implemented in the 2023 photonvision release?

Currently, the [apriltagExample](https://github.com/PhotonVision/photonvision/tree/master/photonlib-cpp-examples/apriltagExample) showcases pose estimation and drivetrain simulation, but only supports HIL (hardware-in-the-loop) simulation of PhotonVision, meaning you would need to plug in a physical camera to your computer and run PhotonVision locally.

**Comment by amquake** [comment]
Moved to #941
