### ISSUE TITLE
Changing the name of a Colored Shape Pipeline

### ISSUE THREAD

**Issue by jasondaming** [PhotonVision/photonvision#335]
When changing the name of a colored shape pipeline the dialog that comes up shows reflective greyed out even if colored shape was previously selected.
![image](https://user-images.githubusercontent.com/15695521/143685269-5704a5bd-0c34-4b42-823a-e86d5ee56b43.png)

**Comment by mcm001** [comment]
Possibly closed by #371 ?

**Comment by mcm001** [comment]
Well the type is gone now, so this issue shouldn't apply. Closing
