### ISSUE TITLE
Switch Photonlib license 

### ISSUE THREAD

**Issue by mcm001** [PhotonVision/photonvision#348]
Consider switching Photonlib to the Wpilib BSD or MIT licenses?

**Comment by gerth2** [comment]
I'm a fan of MIT, but either could work.

From a posturing standpoint, there's not a ton of critical functionality in photonlib, to where I don't see any risk if someone clones it and takes it back into a closed source project . Not really sure why someone would do that anyway.

**Comment by Bankst** [comment]
To do this we just need confirmation from all contributors. That list is
@icemannie @mcm001 @gerth2 @prateekma @calcmogul and @Bankst (myself).

I think MIT license is fine for this, but I'm not married to it. BSD would also be fine

**Comment by icemannie** [comment]
Either one is fine with me.

**Comment by calcmogul** [comment]
You have my permission to use either license.

**Comment by gerth2** [comment]
Permission granted

**Comment by prateekma** [comment]
You have my permission

**Comment by Bankst** [comment]
The license headers in all `photon-lib` source files are still labelled GPL. Will wpiformat correct this with a specific setting?

**Comment by calcmogul** [comment]
You specifically excluded all .java files via `licenseUpdateExclude`. If you wanted wpiformat to do something to some .java files, that's the wrong setting.

**Comment by auscompgeek** [comment]
This is done as of #395, right?

**Comment by Bankst** [comment]
Yes
