### ISSUE TITLE
Limelight Install

### ISSUE THREAD

**Issue by team2194** [PhotonVision/photonvision#355]
The hardware config json file called for in the docs gives the error message "Error while uploading settings file! Could not process provided file."

Exported and unzipped the camera settings, edited the hardwareconfig as attached.

[hardwareConfig.txt](https://github.com/PhotonVision/photonvision/files/7687822/hardwareConfig.txt)

Set "Leds Can Dim" to false since it is a Limelight 2

Now leds will flash and turn off from robot code but won't turn on solid.

**Comment by mcm001** [comment]
What PhotonVision version are you using? And the LEDs should be able to dim. That red modal may not be correct, if you look at the logs it appears to work at least on my end

**Comment by mcm001** [comment]
I just tested with v2021.1.3, works fine
![image](https://user-images.githubusercontent.com/29715865/145482481-6dbbe91f-4114-4a89-b99e-bf008195be5b.png)

**Comment by icemannie** [comment]
I used the latest Gloworm 2021.1.3 per the install docs.
This is on a Limelight 2 and the original config file calls for leds can dim to be false which matches the Limelight specification where the right and left led sections can be controlled separately but not dimmed.
![PhotonVisionNotLoad](https://user-images.githubusercontent.com/19239226/145494726-e5fdcde4-e164-4d13-8bf5-1ca7f7172d2a.png)

**Comment by team2194** [comment]
Started over with gloworm 2021.1.3 flashing he camera with Balena Etcher
Got gloworm.local:5800 in browser and tried the json from the docs with the same result.
Exported the settings zip, unzipped, edited the hardwareconfig, rezipped and imported and the leds work as planned.

Suspect I did something wrong in the rezip before but the same problem still happened with the config from the docs.
