### ISSUE TITLE
First-time lauch funkyness

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision#383]
When running for the first time with the v2022.1.1, on the first launch, the Pi version was detected as "UNKNOWN'. This in turn caused MMAL to not work.

On the second boot, PI_3 was properly detected, but the new pipline was configured with a gain of -1, so the slider didn't show up.

Some time after poking around enough, creating new pipelines, viewing different camera streams, uploading a new .jar ... eventually the gain got set to 50 in the .json, and the slider started showing up.

So, while the problem seems to ultimately be self solving, there's something funky with the first-time launch.

**Comment by gerth2** [comment]
Discord convo [starts here](https://discord.com/channels/725836368059826228/725846797339066379/929902975709745182)

**Comment by mcm001** [comment]
Does this happen every time at first launch?

**Comment by gerth2** [comment]
Sample size of one says "yes". But that's not useful.

Will pull latest and see if it's reproduced there. Really not the end of the world if it's just a "restart once to get mmal" but will watch for it.
