### ISSUE TITLE
Color Threshold with red is near imposible

### ISSUE THREAD

**Issue by 1337-haxxor** [PhotonVision/photonvision#391]
due to the way using HSV works in photonvision, you would need to set a range of around 165-15 ish for the hue but you are unable to do this so in order to use the color red your hue to all possible values if you hue for you red object like the red cargo balls for 2022.

**Comment by Bankst** [comment]
I have thought this over a bit and come up with a possible solution. The idea is to add a toggle to invert the min/max of the range, to allow a hue selection like `330<->15`. This should allow you to capture the red area of the hue circle.

**Comment by 1337-haxxor** [comment]
I would feel that something like that would fix the issue I'm having.

**Comment by jonahsnider** [comment]
This is still a major blocker for vision tracking this year's red cargo. Will this feature be added any time soon?

**Comment by jsimpso81** [comment]
I have seen this also issue. One potential solution is to represent the Hue as a circle -- no beginning and ending.  This way the staring hue value can be selected larger than the ending hue value and it can be displayed.  Also the Hue wheel could be shaded to represent the actual Hue.  (This is an example from LabVIEW...)  
![image](https://user-images.githubusercontent.com/60305400/152878636-58c726ec-f20e-4afc-9ffb-a85f9cb9b9b6.png)

**Comment by Bankst** [comment]
Resolved in [v2022.1.5](https://github.com/PhotonVision/photonvision/releases/tag/v2022.1.5)
