### ISSUE TITLE
Version verification with NetworkTables other than the default NT instance fails

### ISSUE THREAD

**Issue by mcm001** [PhotonVision/photonvision#392]
![image](https://user-images.githubusercontent.com/29715865/149402310-930b145a-3ea5-45a9-8d8a-987b7e884b76.png)
Because versionEntry comes from "mainTable", which is the default NTInstance, passing in your own table doesn't work. Main usecase is simulation, so this bug does not affect real robots.

**Comment by mcm001** [comment]
For now, the suggested workaround is to ignore the warnings as they're wrong I think; long term, the rootTable should change to be the root, then we add `/photonvision` to it to get the camera-specific entries.

**Comment by auscompgeek** [comment]
Fixed per above PR?
