### ISSUE TITLE
Packet::DecodeDouble (in Java) needs to check array length before decoding

### ISSUE THREAD

**Issue by mcm001** [PhotonVision/photonvision#400]
https://github.com/PhotonVision/photonvision/blob/master/photon-targeting/src/main/java/org/photonvision/common/dataflow/structures/Packet.java#L151

This can throw if the provided array is too short.

**Comment by mcm001** [comment]
Packets should check the array provided matches the expected length, and not do anything if not

**Comment by mcm001** [comment]
This is only an issue if people's Photon versions don't match. we should fix anyways

**Comment by KailenC** [comment]
when testing the new photonlib with a previously imaged raspberry pi from last season, we ran into this issue. It would be great if this could be fixed.

**Comment by mdurrani808** [comment]
The fix for now would be to update so both match if you haven't already. @KailenC
