### ISSUE TITLE
Allow changing of CameraPublisher network tables entry to support multiple pi+cameras

### ISSUE THREAD

**Issue by bruingineer** [PhotonVision/photonvision#420]
Currently, We are only able to use one Pi plugged into the network at a time since the CameraPublisher network table entry gets overwritten when there are 2 Pis on the network.

Is there a way to support 2 Pis running photonvision on the same robot?

**Comment by mcm001** [comment]
Do your cameras have the same name? afaik it will not overwrite entries if they do not

**Comment by mcm001** [comment]
per https://github.com/PhotonVision/photonvision/blob/master/photon-core/src/main/java/org/photonvision/vision/frame/consumer/MJPGFrameConsumer.java#L118

**Comment by srimanachanta** [comment]
Unable to reproduce + author abandoned
