### ISSUE TITLE
Pipeline settings data loss on Limelight

### ISSUE THREAD

**Issue by pietroglyph** [PhotonVision/photonvision#434]
Two users on CD have reported pipeline setting loss on the Limelight. Unclear whether or not the pipeline settings are disappearing from the disk or if they're becoming corrupted and being reset because they're unparsable.

**Comment by Bankst** [comment]
This should be fixed by #451

**Comment by Bankst** [comment]
Since the release of 2022.2.0 I have not heard any reports of this. Assuming fixed until otherwise known
