### ISSUE TITLE
What is the default ip address for  photonvision?

### ISSUE THREAD

**Issue by jls667** [PhotonVision/photonvision#460]
I have tried the mdns address photonvision.local:5800, but that does not work. What number could I try? Is there an easy way to just figure out the address?

**Comment by Bankst** [comment]
There is no default IP address. It expects a DHCP server to be on the network to give it one. 

See the linked documentation for finding a device that does not respond to mDNS
https://docs.photonvision.org/en/latest/docs/getting-started/installation/coprocessor-image.html#troubleshooting-setting-a-static-ip

**Comment by gerth2** [comment]
@jls667 any additional feedback on logic that needs to be changed as part of this?
