### ISSUE TITLE
ColoredShape pitch/yaw don't use circle center

### ISSUE THREAD

**Issue by mcm001** [PhotonVision/photonvision#463]
https://www.chiefdelphi.com/t/photonvision-2022-official-release/400536/30?u=thatmattguy
![image](https://user-images.githubusercontent.com/29715865/166088484-c0b8492b-24f7-4372-aae1-4f2887633a51.png)

**Comment by realSaddy** [comment]
I can not replicate this on the latest beta.
![image](https://user-images.githubusercontent.com/31329139/199115436-d603da2b-d129-46af-9e13-0f76fd254473.png)

**Comment by gerth2** [comment]
Based on non replication, @mdurrani808 ok with closing this?

**Comment by mdurrani808** [comment]
Sounds good to me
