### ISSUE TITLE
migrate to apriltags internal homography

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision#470]
and say goodbye to solvePNP

**Comment by gerth2** [comment]
technically should involve:
1) Updating apriltags space to invoke the homography function as part of the detect pipeline
2) Add new stuff to the JNI to pass the new matricies in for camera distoration and get both results back out
3) add new stuff to the aurco java pipeline to pass in the required params from the camera
4) add new stuff to the aurco java pipeline to read both results,a nd pick the one with lower error

**Comment by shueja-personal** [comment]
Solved.
