### ISSUE TITLE
simposeest imageCaptureTime incorrect

### ISSUE THREAD

**Issue by agasser** [PhotonVision/photonvision#498]
In the Java simposeest example, the [`DrivetrainPoseEstimator`](https://github.com/PhotonVision/photonvision/blob/master/photonlib-java-examples/src/main/java/org/photonlib/examples/simposeest/robot/DrivetrainPoseEstimator.java#L89) is miscalculating `imageCaptureTime`.

```
double imageCaptureTime = Timer.getFPGATimestamp() - res.getLatencyMillis();
```

`Timer.getFPGATimesptamp()` returns the current time in seconds, but `res.getLatencyMillis()` is in miliseconds.

I believe this should be
```
double imageCaptureTime = Timer.getFPGATimestamp() - res.getLatencyMillis() / 1000; 
```

**Comment by mcm001** [comment]
Yup, good catch. PRs welcome -><-
