### ISSUE TITLE
WS Camera Streams - add global setting for what style of camera streams to use

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision#545]
Currently, the camera streams always broadcast both mjpeg and websocket protocols. Users should only need one at a time.

1) Update the settings page to have a dropdown switch for users to select
2) Save the selection to settings like the others
3) Add logic on the JS side for the cv-image template to swithc between websocket and mjpeg streaming based on the setting
4) Add logic internally to VisionModule.java and SocketVideoStream*.java classes to optimize and only process/send the required protocol.

**Comment by mdurrani808** [comment]
Closed by #645
