### ISSUE TITLE
WS Camera Streams - Add protocol for querying active streams

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision#546]
Add a protocol where a client can query what streams (port-id's, camera names, etc.) are currently active.

Thinclient should call this periodically and update its UI to allow the user to "select from available", rather than just having to know or guess the port.

**Comment by mdurrani808** [comment]
Closed by #645

**Comment by srimanachanta** [comment]
Is this still applicable with the thinclient removal? When would a user need to know stream ports outside of the dashboard itself, exactly where they would access the same reqeust.
