### ISSUE TITLE
WS Camera Streams - improve thinclient architecture

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision#547]
Currently,the websocket video stream code is dual maintained - once in the actual WebsocketVideoStream.js plugin, again inside the single-html thinclient.

Re-work the build and architecture such that:
1) there is only one copy of the websocket video streaming logic
2) the thinclient can still be downloaded as a all-in-one html file (preventing browser cross-origin errors)

**Comment by mdurrani808** [comment]
Closed by #645

**Comment by srimanachanta** [comment]
thinclient was removed
