### ISSUE TITLE
Photon Pipeline Index

### ISSUE THREAD

**Issue by icemannie** [PhotonVision/photonvision#564]
Java getPipelineIndex() returns the pipeline number selected on the UI.

Java setPipelineIndex(n) (n exists) does not cause the pipeline selection on the UI to change.

It does cause the getPipelineIndex() to return the n value. Changing the pipeline on the UI will cause the getPipelineIndex() to return the value of the UI pipeline.

If in Driver Mode on the UI, setting a pipeline number will turn the getDriverMode() to false but won't change the UI switch

**Comment by mcm001** [comment]
I suspect all we need is a broadcast full settings call in the handler for setting the pipeline index on a NT change

**Comment by icemannie** [comment]
Issue #563 has a similar pron

**Comment by mcm001** [comment]
I think making the backend emit a full settings update when the pipeline index is changed over NT should do it

**Comment by mcm001** [comment]
```        DataChangeService.getInstance()
                .publishEvent(
                        new OutgoingUIEvent<>(
                                "fullsettings", ConfigManager.getInstance().getConfig().toHashMap()));```
