### ISSUE TITLE
Sim Photon Camera populating NT Version entry under wrong heading

### ISSUE THREAD

**Issue by edf42001** [PhotonVision/photonvision#568]
This is similar to issue #415, which led to fix #424. However, PhotonCamera expects versionEntry under the mainTable

https://github.com/PhotonVision/photonvision/blob/b408a58e9eeaa56f29e7572a0394cbd44c1acb2e/photon-lib/src/main/java/org/photonvision/PhotonCamera.java#L77

But the SimPhotonCamera looks for it under rootTable. Also it looks for `"versionEntry"` instead of `"version"`.

https://github.com/PhotonVision/photonvision/blob/b408a58e9eeaa56f29e7572a0394cbd44c1acb2e/photon-lib/src/main/java/org/photonvision/SimPhotonCamera.java#L64

So the issue of `"PhotonVision coprocessor at path " + path + " not found on NetworkTables!"` persists.

**Comment by mdurrani808** [comment]
Closed by refrenced PR.
