### ISSUE TITLE
Toggling driver mode defaults to the 1st pipeline rather than the last used one 

### ISSUE THREAD

**Issue by mcm001** [PhotonVision/photonvision#594]
https://discord.com/channels/725836368059826228/725846784131203222/1041108867968405565

**Comment by Birb12** [comment]
Hi, would love to take a shot at this. Any idea as to what file the issue originates from? Pretty new to the codebase. Thanks.

**Comment by mcm001** [comment]
Awesome! My first thought would be to poke at the pipeline manager which is located here: https://github.com/PhotonVision/photonvision/blob/master/photon-core/src/main/java/org/photonvision/vision/processes/PipelineManager.java
