### ISSUE TITLE
Unexpected camera exposure behavior on Arducam OV9281 USB Camera

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision#599]
a camera with name `Arducam OV9281 USB Camera` is doing weird exposure things: 

![image](https://user-images.githubusercontent.com/4583662/201820699-a0600de2-90f4-4217-8643-fe68069ff72f.png)

Assuming cscore will take it, remap full slider range to 0.4-0.5 ?

**Comment by gerth2** [comment]
https://discord.com/channels/725836368059826228/725847316707147808/1041921478989459546 Actually, looks like it might be futile. the difference seems to happen as the values `0` or `1` (out of a 0-100 range) are passed into cscore's `setExposureManual()`

**Comment by gerth2** [comment]
![image](https://user-images.githubusercontent.com/4583662/201822658-5c7bacbd-b2a3-4d0d-8982-201d5ce229bd.png)

**Comment by asid61** [comment]
fixes did not work yet. I am willing to send my OV9281 to anyone who wants to debug it...

**Comment by mdurrani808** [comment]
@asid61 fix landed in https://github.com/wpilibsuite/allwpilib/commit/149bac55b1a419ca7ed52db9f3f06807ff9a6108
Should be out whenever we cut a new release.

**Comment by gerth2** [comment]
Based on discord comments I think it's safe to close this. Can always reopen.
