### ISSUE TITLE
Calibration distortion coefficients mislabelled as extrinsics

### ISSUE THREAD

**Issue by amquake** [PhotonVision/photonvision#601]
Calibration coefficients constructor:

https://github.com/PhotonVision/photonvision/blob/4c004fc7809ab4c76312bff4c2f3dde97dcb70a6/photon-core/src/main/java/org/photonvision/vision/calibration/CameraCalibrationCoefficients.java#L45-L50

Its usage in the calibration pipe:

https://github.com/PhotonVision/photonvision/blob/4c004fc7809ab4c76312bff4c2f3dde97dcb70a6/photon-core/src/main/java/org/photonvision/vision/pipe/impl/Calibrate3dPipe.java#L133-L134

Camera Extrinsics:
> ...transformation from the world coordinate system to the camera coordinate system is called camera extrinsics or camera pose

We don't set camera extrinsics as we consider each target relative to the camera (and the user can use this on their side to determine world coordinates afterwards). In the calibration coefficients/config file, though, the distortion coefficients are incorrectly referred to as extrinsics.

**Comment by mcm001** [comment]
Is there a way to fix this without breaking everyone's calibrations theyve already done?
