### ISSUE TITLE
Change Default tag family to 16H11 & 16h11 size spec

### ISSUE THREAD

**Issue by mperino** [PhotonVision/photonvision#604]
![image](https://user-images.githubusercontent.com/3091956/202322877-a363c656-aaf1-4a0f-aa05-12ce47feb05f.png)
![image](https://user-images.githubusercontent.com/3091956/202322947-b406d1f2-4729-4093-b7ce-79c585e1cf92.png)
New install of 2023.1.1-beta-6 sees 36h11 tags just fine, but tried an 8in x 8in tag from:
https://github.com/AprilRobotics/apriltag-imgs/tree/master/tag16h5
specifically tag "07" 

As you can see in the screenshot, it finds and detects the 36h11 tag "42" with no problem..  Regardless of weather there are one or two tags in the FOV it is the same result.  Is there something that I need to do manually to force which family it is detecting?

**Comment by gerth2** [comment]
Yes - under the Apriltags tab, there's a selector for which family. Only one family is detected at a time (the tag ID's overlap).

![image](https://user-images.githubusercontent.com/4583662/202334359-422bb355-9acd-4d19-b5a8-737c4732e7cb.png)


Give this a shot to see if it fixes up the issue, let us know!

**Comment by mperino** [comment]
That fixed it!  Can we make the default tag 16h5 instead of 36h11.
OK to close the issue as fixed.

**Comment by gerth2** [comment]
I think switching the default would be ideal. I'll make sure we get an issue in for it - timing wise, I'd expect it should probably be pulled off in whatever release is closest to right before kickoff.

**Comment by gerth2** [comment]
Per new title - prior to kickoff, change to the kickoff spec tag family

**Comment by gerth2** [comment]
Closed by #652
