### ISSUE TITLE
Multicamera doesn't work with two of the same cameras

### ISSUE THREAD

**Issue by mdurrani808** [PhotonVision/photonvision#623]
Fix would be to reference cameras based on their ports rather than their name.

**Comment by asid61** [comment]
To elaborate on this, this problem was consistent with AR0144 cameras, which cannot be renamed using the Arducam utility. Would be really nice if we could run multiple of these.

**Comment by mdurrani808** [comment]
@drakeerv Due to how thorough this change would be, we are planning on pushing the fix to next season. For now, just use two different cameras. You should do something other than a Lifecam for apriltags in general

**Comment by fovea1959** [comment]
not sure this is a big change on Linux. use the /dev/v4l/by-path paths to access cameras....

**Comment by mcm001** [comment]
I believe this issue is OBE, but reopen if not!
