### ISSUE TITLE
occasionally disconnecting from rpi

### ISSUE THREAD

**Issue by SammyPants37** [PhotonVision/photonvision#631]
I'm not sure if I'm meant to be using it this way but I am connected to a rpi running photonvison via ethernet and the dashbord will somewhat regularly stop responding. I am running 2023 beta 6 on a pi 4

**Comment by SammyPants37** [comment]
I am off robot and running dchp (assuming it isn't static with a fresh install)

**Comment by mdurrani808** [comment]
Is your Pi plugged into a router or your computer?

**Comment by mdurrani808** [comment]
If into a computer, plug it into a router. If its in a router already, check your power supply and send the logs to make sure nothing is crashing.

**Comment by SammyPants37** [comment]
I shall try plugging it into the router. now should I connect directly to the router or is the wifi network fine
________________________________

**Comment by mcm001** [comment]
WDYM "stop responding", exactly?

**Comment by SammyPants37** [comment]
the camera feed will show a loading gif and it will stop showing targets (I haven't tried out code yet) either giving it time or unplugging the ethernet and plugging back in fixes it I'm not quite sure what.
________________________________

**Comment by mdurrani808** [comment]
Wifi isn't enabled on PhotonVision, plug the Pi directly into the router and then access the webdashboard on a computer on the same network.

**Comment by SammyPants37** [comment]
I meant more weather to connect to the router via ethernet or wifi but I'm guessing that doesn't matter too much
________________________________

**Comment by mdurrani808** [comment]
Any updates?

**Comment by SammyPants37** [comment]
I have moved to a limelight with photonvision that is connected to a robot and I don't think I've ran into connection problems

________________________________
