### ISSUE TITLE
HD-3000 Loads forever but still gets an output

### ISSUE THREAD

**Issue by SauquetAlex** [PhotonVision/photonvision#639]
On the dashboard, the HD-3000 camera loads forever (unreliably and only sometimes) but still gives good outputs. Kinda weird.

**Comment by gerth2** [comment]
Will likely be closed by https://github.com/PhotonVision/photonvision/pull/624

**Comment by mcm001** [comment]
@SauquetAlex could you try again with beta 8?

**Comment by SauquetAlex** [comment]
Hey there, we didn't see such bug on the last releases, so looks good to me!
