### ISSUE TITLE
outputSaveImgCmd and inputSaveImgCmd is not reset to false when calling takeOutputSnapshot() or takeInputSnapshot() twice in a row

### ISSUE THREAD

**Issue by LuminousLlama** [PhotonVision/photonvision#662]
I have takeOutputSnapshot() and takeInputSnapshot() bound to buttons on an Xbox controller. 

The first time I press the button it works fine, setting the values to true and then back to false automatically. 

However, if I press the button again it sets the value to true and does not set it back to false again. If I manually set it to false in Glass and then press the button it works the first time and gets stuck on true again the second time. 

I first brought this up here
https://discord.com/channels/725836368059826228/753739620050665523/1057441674873286749

**Comment by gerth2** [comment]
Closed by #664
