### ISSUE TITLE
JAVA backend quit unexpectedly

### ISSUE THREAD

**Issue by FUNDAI** [PhotonVision/photonvision#663]
After "Settings Saved ! " ,  java backend can't insist for a long time , i can't even key the team number , then just jump out . 
[photonvision-2022-12-29_07-30-25.log](https://github.com/PhotonVision/photonvision/files/10319180/photonvision-2022-12-29_07-30-25.log)

**Comment by mdurrani808** [comment]
If you click the settings multiple times in a row, it is possible for the backend to crash. Otherwise, more explanation would be necessary.

**Comment by FUNDAI** [comment]
> If you click the settings multiple times in a row, it is possible for the backend to crash. Otherwise, more explanation would be necessary.

I record the situation what I met  , and the red line is
 "[2023-01-02 19:10:44] [General - NetworkTablesManager] [ERROR] [NetworkTablesManager] Could not connect to the robot! Will retry in the background..." 
https://user-images.githubusercontent.com/96116846/210223916-1fc31bf0-ce68-41c8-bb3b-189bcfeb0d80.mp4

**Comment by gerth2** [comment]
> Could not connect to the robot! Will retry in the background..."
This should be expected if there is no roboRIO running a Network Tables server.

Unfortunately this one is strange, I haven't seen behavior  like this before. The log shows it's running a one-off dev build from a few releases back. Does the [beta 7](https://github.com/PhotonVision/photonvision/releases/tag/v2023.1.1-beta-7) release have the same behavior?

**Comment by FUNDAI** [comment]
> > Could not connect to the robot! Will retry in the background..."
> 
> This should be expected if there is no roboRIO running a Network Tables server.
> 
> Unfortunately this one is strange, I haven't seen behavior like this before. The log shows it's running a one-off dev build from a few releases back. Does the [beta 7](https://github.com/PhotonVision/photonvision/releases/tag/v2023.1.1-beta-7) release have the same behavior?

Oh , when I update to beta 7 it fixed but when you enabled your built-in Webcam , it will show the error message 
"[2023-01-03 23:50:15] [VisionModule - VisionRunner - USBFrameProvider - opencv_USB2.0_HD_UVC_WebCam] [ERROR] Exception on loop 588" and crash  , however I think this not a big deal just disabled it and it can work normally 
, and thank you for solving my problem.

**Comment by mcm001** [comment]
Sounds like we're good now? Closing the issue but feel free to reopen if you have more trouble
