### ISSUE TITLE
possible bug in photon-client

### ISSUE THREAD

**Issue by srimanachanta** [PhotonVision/photonvision#667]
https://github.com/PhotonVision/photonvision/blob/15fbe29d34e7000523f8a3709007540a901ed16c/photon-client/public/thinclient.html#L307

should this be &&?

**Comment by mcm001** [comment]
Not a bug, logically it works fine. Probably a typo tho

![image](https://user-images.githubusercontent.com/29715865/210096378-1ca21c3a-ef61-4387-9165-c53a11aa1963.png)
