### ISSUE TITLE
[photon-lib] RobotPoseEstimator::SetPoseStrategy is unimplemented

### ISSUE THREAD

**Issue by auscompgeek** [PhotonVision/photonvision#676]
The `RobotPoseEstimator::SetPoseStrategy` method is declared here:

https://github.com/PhotonVision/photonvision/blob/dc663657ff90c9adc453ef87c1155f63ef6e1a6e/photon-lib/src/main/native/include/photonlib/RobotPoseEstimator.h#L61

However it doesn't appear to be implemented anywhere.

**Comment by mcm001** [comment]
Closed by #677
