### ISSUE TITLE
[photonLib] [documentation] Inconsistency between SimVisionSystem and RobotPoseEstimator docs

### ISSUE THREAD

**Issue by TandeJ** [PhotonVision/photonvision#695]
RobotPoseEstimator's documentation states that the transforms given in the contructor should be from the robot frame of reference to the camera frame.
SimVisionSystem wants the opposite in its docs, stating that it wants a camera -> robot transformation.

This isn't a big issue, I just called `inverse()` on the transform where needed-- but I could see it really biting a good number of people who don't read the docs close enough in the back.

**Comment by mdurrani808** [comment]
Awesome find! Do you mean in the JavaDoc or the docs.photonvision.org?
