### ISSUE TITLE
Camera stream sometimes doesn’t appear on page load

### ISSUE THREAD

**Issue by pietroglyph** [PhotonVision/photonvision#70]
https://discord.com/channels/176186766946992128/528555967827148801/740329176246255720

**Comment by mcm001** [comment]
#136 has made this more robust, though it can sometimes still happen.

**Comment by mcm001** [comment]
Seems like firefox may sometimes just refuse to make the websocket connection sometimes? And sometimes it's slow?

**Comment by gerth2** [comment]
I'm gonna go out on a limb and say Closed by #529
