### ISSUE TITLE
Target grouping by intersection is broken

### ISSUE THREAD

**Issue by prateekma** [PhotonVision/photonvision#72]
![image](https://user-images.githubusercontent.com/19977330/89479537-186fc880-d761-11ea-9b14-04800fbb63e6.png)

**Comment by Bankst** [comment]
This is a frontend issue. It is not sending the proper command to the backend.

**Comment by mcm001** [comment]
Fixed in frontend. 
![image](https://user-images.githubusercontent.com/29715865/89572115-8e197a00-d7dd-11ea-81a2-8bd22bdf3d0a.png)

**Comment by mcm001** [comment]
See #75
