### ISSUE TITLE
Edit Pipeline Names  Index is off by one.v2023.1.2 (and prior)

### ISSUE THREAD

**Issue by icemannie** [PhotonVision/photonvision#725]
As an example case, assume existing pipelines A,B and C indices 0,1 and 2.

Trying to edit name C brings up the B name in the edit field. Similarly trying to edit B brings up A.

‘Trying to edit A brings up a blank edit field.

**Comment by mcm001** [comment]
Seems like an easy off by one fix -- wanna take a stab? https://github.com/PhotonVision/photonvision/blob/357d8a518a93f7a1f8084a79449249e613b605a7/photon-client/src/components/pipeline/CameraAndPipelineSelect.vue#L367

**Comment by icemannie** [comment]
I’ll see what I can do. No guarantees though.

**Comment by srimanachanta** [comment]
resolved in new UI
