### ISSUE TITLE
PhotonVision camera feed freezes on AprilTag 3d mode enable

### ISSUE THREAD

**Issue by superpenguin612** [PhotonVision/photonvision#737]
Enabling 3D AprilTag detection for the first time causes camera feed to freeze whenever an AprilTag is in frame (feed comes back when tag is removed from frame), reboot fixes the issue and it doesn't appear again.

Steps to reproduce:
1. install the v2023.1.2-linuxarm64-image_RaspberryPi image on an rpi 4 model b
2. boot up pi/pv, everything is connected via ethernet on a test bench
3. plug in a OV9281 camera
4. set pipeline to apriltags (2d)
5. calibrate camera
6. switch apriltag mode to 3d

**Comment by mcm001** [comment]
Just tried on my Pi but couldn't reproduce. Switched to apriltag 2d pipeline at 640x480, calibrated at 960x720, switched to apriltags at 960x720, and enabled 3d.

**Comment by superpenguin612** [comment]
Did you have an AprilTag in view, and was it able to render the 3d box around it? The same issue happened again after we reset our Pi due to an unrelated problem.

**Comment by mcm001** [comment]
Yes, apriltag in view the whole time. Box was rendered right away for me.

**Comment by superpenguin612** [comment]
Interesting, I will try to reproduce again the next time I can.

**Comment by srimanachanta** [comment]
@superpenguin612 is this still relevant?

**Comment by superpenguin612** [comment]
Not still relevant as far as I can tell, must have been fixed at some point.
