### ISSUE TITLE
Allow PhotonPoseEstimator to handle multiple cameras

### ISSUE THREAD

**Issue by realSaddy** [PhotonVision/photonvision#744]
RobotPoseEstimator supports multiple cameras. Its replacement, PhotonPoseEstimator, doesn't. It is very useful to allow PhotonPoseEstimator to use multiple cameras. Not sure why that functionality was removed

**Comment by srimanachanta** [comment]
Certain strategies don't support it. The average one doesn't rely on data from one camera. Also, most teams are using this in conjunction with WPI's pose estimators. Those filters can accept multiple "good" positions that don't require a wrapper to return a single pose.
