### ISSUE TITLE
Packet Missing Camera Information

### ISSUE THREAD

**Issue by joecaraccio** [PhotonVision/photonvision#752]
Hi Everyone!

Love this software! So were getting some good target information back from our Camera. The Yaw, Pitch, Area, Id all look good.

However, the BestCameraToTarget transform is blank (which ruins our calculations in the RobotPoseEstimator too). The values decoded from the packet are all 0s. I can't understand why. I'd suspect we are missing some configuration with our system, but I'd also suspect that all that info is already used to calculate yaw correctly wherever it is that.

It looks like my java version and my photoVision version running on my rpi are equivalent. My camera has a FOV set.

Any ideas why all the bytes used to decode that packet are zero? what am I doing wrong?

`    public Packet createFromPacket(Packet packet) {
        this.yaw = packet.decodeDouble();
        this.pitch = packet.decodeDouble();
        this.area = packet.decodeDouble();
        this.skew = packet.decodeDouble();
        this.fiducialId = packet.decodeInt();

        this.bestCameraToTarget = decodeTransform(packet);
        this.altCameraToTarget = decodeTransform(packet); `

**Comment by mdurrani808** [comment]
Cleared up elsewhere, but you need to have 3D mode enabled (which means you need a calibrated camera).
