### ISSUE TITLE
Add Multi Tag PNP similar to Limelight MegaTag

### ISSUE THREAD

**Issue by mdurrani808** [PhotonVision/photonvision#757]

**Comment by prensing** [comment]
I would like to see this too.  I think the added "lever arm" of computing position based on 2 tags could be really powerful

**Comment by prensing** [comment]
An alternate suggestion (they are not mutually exclusive) would be to implement the existing strategies but for individual tag IDs. So, if a camera sees 2 tags, update the PoseEstimator once for each tag, using one of the existing strategies to resolve any ambiguity.

**Comment by MrRedness** [comment]
Closed by #787 ?

**Comment by mcm001** [comment]
Closing for now, as it technically exists. Long term I'd like it moved to the coprocessor tho
