### ISSUE TITLE
Camera stream doesn't load - Limelight 2023.2.2

### ISSUE THREAD

**Issue by StephenDay1** [PhotonVision/photonvision#782]
We just put the new image on the limelight and it boots properly, unlike with the previous images.  However, at photonvision.local:5800, the camera stream is just yellow with a loading animation.

We have restarted the limelight several times, and refreshed the page several times as well, nothing changes.

**Comment by TheOven2** [comment]
We have the exact same problem.

**Comment by mcm001** [comment]
New pi image pulled in libcamera 0.0.3, but we build against 0.0.2, and our old pi image does as well. That's fun. Working on a fix -- you can for now downgrade the libcamera package down to 0.0.2 for a quick fix over ssh

**Comment by mcm001** [comment]
Try `sudo apt install libcamera0=0~git20230105+5df5b72c-1`?

**Comment by mcm001** [comment]
Or try an offline update using a JAR from https://github.com/PhotonVision/photonvision/actions/runs/4059890146

**Comment by mcm001** [comment]
Are either of you able to try the latest development release?

**Comment by StephenDay1** [comment]
Development release works. Thank you!
