### ISSUE TITLE
AprilTagExample is never updated to 2023

### ISSUE THREAD

**Issue by StephenDay1** [PhotonVision/photonvision#803]
There is a TODO comment inside of [PhotonCameraWrapper.java](https://github.com/PhotonVision/photonvision/blob/master/photonlib-java-examples/apriltagExample/src/main/java/frc/robot/PhotonCameraWrapper.java) saying "once 2023 happens, replace this with just loading the 2023 field arrangement" right next to where the AprilTagFieldLayout is loaded.

I followed this example with my team, and I tried to go ahead and directly use the field layout myself:
`fieldLayout = new AprilTagFieldLayout(AprilTagFields.k2023ChargedUp.m_resourceFile);`

When I do this though it throws a FileNotFoundException.  I don't know if I'm doing something wrong, or if this is an issue that should be shown to WPILib, but if this example was updated it would be helpful.

**Comment by mcm001** [comment]
Closed by #807
