### ISSUE TITLE
3D can be enabled without any valid calibrations

### ISSUE THREAD

**Issue by Bankst** [PhotonVision/photonvision#82]

**Comment by pietroglyph** [comment]
I have a pretty good picture in my mind for how this should be dealt with in the UI, so I'll self-assign.

**Comment by mcm001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Don't allow 3d if not calibrated](https://trello.com/c/fka9X0k2/96-dont-allow-3d-if-not-calibrated)
