### ISSUE TITLE
[example] simposeest has constant declaration error

### ISSUE THREAD

**Issue by srimanachanta** [PhotonVision/photonvision#838]
https://github.com/PhotonVision/photonvision/blob/dcd917870cece9e34eb32bf7ddc068d52dc5aefa/photonlib-java-examples/simposeest/src/main/java/frc/robot/DrivetrainSim.java#L91

This should be robotToCamera and not cameraToRobot

**Comment by amquake** [comment]
The `simposeest` example was removed in #913
