### ISSUE TITLE
text overlaps in photon-client log viewer

### ISSUE THREAD

**Issue by srimanachanta** [PhotonVision/photonvision#882]
Currently in the client, because v-virtual-scroll is used with a fixed item height, certain longer messages (such as the calibration message) overlap. Perhaps change the font to fit the item div's height.

<img width="1394" alt="image" src="https://github.com/PhotonVision/photonvision/assets/68172138/fbf6855e-a98f-4257-b4c4-396aa76cb91b">

**Comment by Juniormunk** [comment]
Fixed with https://github.com/PhotonVision/photonvision/pull/1385
