### ISSUE TITLE
Pi4 startup loop

### ISSUE THREAD

**Issue by amquake** [PhotonVision/photonvision#917]
Deploying latest PV to a pi4 causes a startup loop-- the backend connects for half a second before restarting.

[log.txt](https://github.com/PhotonVision/photonvision/files/12699192/out.txt)

It seems to have started on this commit: https://github.com/PhotonVision/photonvision/commit/306677e56fef17c21f2cf0415fcd963f3159a877

**Comment by mcm001** [comment]
Yeah, I'm officially confused. How does that commit affect our camera hardware at all?

**Comment by amquake** [comment]
I'm also confused, it doesn't look like this should be capable of causing this. Checking out the commit before works, but this commit doesn't. I believe I flashed with latest dev first and saw this, I didn't find this commit until deploying an earlier commit fixed the problem.

**Comment by amquake** [comment]
I only found [this](https://github.com/raspberrypi/picamera2/issues/576) issue related to the same error. If its similar, it has to do with attempting to start the camera without closing its previous usage (still don't know _why_ this would happen on this commit).

What's the purpose of the camera being started/stopped several times on bootup? You can see this in the log from photon-libcamera as "Starting camera", "stopping all", "stopped all", and "Destroying headless".

**Comment by mcm001** [comment]
Seems like on boot the camera changes resolutions a bunch of times. This has happened since the driver was first added, and could probably be made better

**Comment by amquake** [comment]
Okay... If I make [`NetworkUtils.getAllInterfaces()`](https://github.com/PhotonVision/photonvision/commit/306677e56fef17c21f2cf0415fcd963f3159a877#diff-98cf7fbd5e66d009540a2a4415bbd51e17f7d2b41548a679112572211a63c540R78) return immediately (avoiding any of the shell commands for finding network interfaces) it boots up without crashing. If I had to guess, this is something with the executed commands blocking the camera acquisition somehow?

**Comment by amquake** [comment]
https://github.com/amquake/photonvision/tree/pi-startup-fix I just made a quick hacky fix that caches the interface read (`"nmcli -t -f GENERAL.CONNECTION,GENERAL.DEVICE,GENERAL.TYPE device show"`) to once every 5 seconds since it gets called a lot. Not sure if this could cause problems (does this shell command return new values depending on e.g. new ethernet connections? or does that fall under `getAllActiveInterfaces()` filtering?). Still don't like how this can cause this error in the first place, but I'm not sure how to get more info about that.

**Comment by mcm001** [comment]
Also, longer term, this could migrate to talking dbus directly to networkmanager, or being a native library?
