### ISSUE TITLE
Remove ChameleonVision naming scheme

### ISSUE THREAD

**Issue by mdurrani808** [PhotonVision/photonvision#922]
Some UI components (cv-slider for example) and core components (CVMat) are prefixed with CV (standing for chameleon vision). This distinction is no longer relevant and should either be renamed to PV(object) or the code should be removed if it is no longer used.

**Comment by srimanachanta** [comment]
Thats what that means? I just carried that forward cause it helped distinguish custom UI comps. I would say rename CV -> PV then.
