### ISSUE TITLE
PhotonPoseEstimator's estimated pose has different origin depending on number of tags in view

### ISSUE THREAD

**Issue by mjansen4857** [PhotonVision/photonvision#991]
**Describe the bug**
When using PhotonPoseEstimator with the multi tag on coprocessor strategy, the origin of the estimated pose will always have a blue alliance origin if multiple tags are in view. But, if only one tag is in view, the estimated pose will have an origin matching the AprilTagFieldLayout given to the pose estimator.

**To Reproduce**
1. Load the 2023 AprilTagFieldLayout and set a red alliance origin
2. Create a PhotonPoseEstimator with the above tag layout and a multitag on coprocessor strategy
3. Observe the estimated pose when multiple tags are in view as having a blue origin
4. When one tag is in view, the estimated pose will have a red origin, matching the tag layout

**Screenshots / Videos**
Using AdvantageScope to visualize the issue here. The robot's alliance is currently set to red, so the tag layout given to the pose estimator has a red origin. I am transforming the estimated pose from blue to red to match the current alliance, which is why the pose with a red alliance origin ends up on the blue side of the field. 

https://github.com/PhotonVision/photonvision/assets/9343077/bfb48447-7348-45fe-86ec-76ed10e79de7

**Platform:**
 - PhotonLib Version: 2024.1.1-beta-1

**Additional context**
I am running in simulation here using VisionSystemSim, but I believe this will apply to real results as well based on the PhotonPoseEstimator using the given tag layout if there is no multitag result.

**Comment by amquake** [comment]
@mjansen4857 can you check if #997 behaves correctly?
